#define SPIDER_VERSION "v0.2.1"

#define SPIDER_DEFAULT_OK_ADDRESS 125
#define SPIDER_DEFAULT_OK_NUM      11

#define SPIDER_DEFAULT_STA_SSID     "default"
#define SPIDER_DEFAULT_STA_PASSWD   "11111111"

#define SPIDER_DEFAULT_AP_SSID     "SpiderBOT"
#define SPIDER_DEFAULT_AP_PASSWD   "11111111"

#define SPIDER_DEFAULT_MDNS   "spiderbot"
